### ISSUE TITLE
warum selbst neu programmieren, wenn es dafür gut abgehangene OSS gibt

### ISSUE THREAD

**Issue by rtt-mmk** [ToolboxBodensee/toolbox-wiki#1]
https://github.com/ToolboxBodensee/toolbox-webseite/pull/463#issuecomment-554744543

**Comment by DO1JLR** [comment]
das hier ist weder selber programiert noch der OSS!
> Das Office of Strategic Services war von 1942 bis 1945 ein Nachrichtendienst des Kriegsministeriums der Vereinigten Staaten

**Comment by rtt-mmk** [comment]
also das dokuwiki der Toolbox gibt es dazu schon lange. und auch wieder unter wiki.byt3.de

mediawiki wäre ein anderer Vertreter von OSS - in dem es [dazu](https://en.wikipedia.org/wiki/OSS) auch gaaanz viel Inhalt gibt. 

Schön Lilian, dass du unwichtige, ablenkende völlig unrelavante Kriegsfakten dazu rausgesucht hast.

Zielführend wäre aber trotzdem das vorhandene Wiki einfach wieder zu betreiben. Wie wäre es, wenn du bitte dazu einfach mal das passenden DNS-Alias/CNAME setzten würdest.

**Comment by rtt-mmk** [comment]
Die beiden wichtigsten Fragen sind leider wie immer von Dir diesbezüglich bis heute nicht beantwortet worden:
> Ihr übernehmt dann auch alle Inhalte vom Wiki in das neue selbst programmierte?
> Und habt dort integriert einen Markup-Seiteneditor (oder WYSIWYG) in dem auch jedes Mitglied das Wiki editieren kann?

**Comment by DO1JLR** [comment]
> also das dokuwiki der Toolbox gibt es dazu schon lange. und auch wieder unter wiki.byt3.de
> 
> mediawiki wäre ein anderer Vertreter von OSS - in dem es [dazu](https://en.wikipedia.org/wiki/OSS) auch gaaanz viel Inhalt gibt. Vornehmlich natürlich unter "Computer software and hardware".
> 
> Zielführend wäre aber trotzdem das vorhandene Wiki einfach wieder zu betreiben. Wie wäre es, wenn du bitte dazu einfach mal das passenden DNS-Alias/CNAME setzten würdest. Siehe wiki.byt3.de
> 
> (Schön Lilian, dass du unwichtige, ablenkende völlig unrelavante Kriegsfakten dazu rausgesucht hast. Dann weißt du sicher auch, dass der OSS Deutsche und Österreicher trainiert hat, um Nazi-Deutschland zu unterwandern. Vielleicht nützliches Wissen für deinen weiteren Weg, hier aber völlig fehl am Platz.)

Ist der erste Platz bei der duckduckgo suche:
https://lmgtfy.com/?q=OSS&s=d

**Comment by DO1JLR** [comment]
> Die beiden wichtigsten Fragen sind leider wie immer von Dir diesbezüglich bis heute nicht beantwortet worden:
> 
> > Ihr übernehmt dann auch alle Inhalte vom Wiki in das neue selbst programmierte?
> > Und habt dort integriert einen Markup-Seiteneditor (oder WYSIWYG) in dem auch jedes Mitglied das Wiki editieren kann?

Wo bitte sind die da gestellt.

Du stellst da irgend welche links ins internet und erwartest nicht wirklich, das ich so dumm bin und da drauf klicke?

**Comment by DO1JLR** [comment]
Zu deiner Frage der Übernahme:

Selbstverständlich übernimmt die Toolbox **nicht** alle Inhalte aus der alten Wikiinstanz. Sondern nur diese, die Zeitlch noch aktuell sind. Was soll man mit veralteten Inhalten?

Zu der Editorfrage. Schau es dir an. Finde es selber raus. Wenn nicht... Klicke auf den Link, der dich auch eine Hilfeseite führt: [Editor benutzen für einsteiger](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository)

**Comment by xythobuz** [comment]
@DO1JLR Bitte, langsam wirds einfach lächerlich.

Du weißt genau was @rtt-mmk gemeint hat, wir alle wissen das, du willst nur wie ein trotziges Kleinkind nicht drauf eingehen.

Ich stimme absolut zu: du kannst von non-IT Toolbox Mitgliedern nicht erwarten das sie git und github verwenden. Das ist für ein Vereins-Wiki absolut unpraktikabel.

Aber leider scheint eine sinnvolle Diskussion hier nicht mehr möglich zu sein. Sehr schade.

**Comment by DO1JLR** [comment]
Letzten Donnerstag war das noch ganz anders und Falko konnte sich das noch relativ gut vorstellen.

Das Problem ist, dass ohne Beispiel sich die Leute das nicht vorstellen können, sondern nur scheiße finden... Also braucht es ein Beispiel, da man sonst nicht miteinander reden kann, da jeder von etwas anderen spricht.

Der Github Editor ist nicht schwerer zu bedienen wie der Dokuwiki editor. Es sind alle gewöhnungssache. Und alle nicht perfekt.

Und was der @rtt mit seinem OSS meint, weiß ich tatsächlich nicht. Ich habe den Begriff daher wirklich gegoogelt. Und wirklich das gefunden, was ich da oben verlinkt habe. Sorry. Er hat angefangen Nazivereine hier zu verwenden. Nicht ich.

**Comment by xythobuz** [comment]
OSS steht fuer "open source software". Das hat @rtt-mmk oben auch nochmal ausgeführt und auf den entsprechenden Wikipedia Artikel verwiesen.

Also red dich doch nicht mit so offensichtlichem Bullshit raus. Mag ja sein das das wirklich keine böse Absicht von dir war. Aber nach aussen hin wirkt all dein Verhalten als würdest du nur noch trollen wollen und n fick auf alle anderen Meinungen geben.

Das macht Vereinsleben nicht gerade angenehm, und wenn es dann auch noch um die "hoheitlichen" Aufgaben geht für die du gewählt wurdest dann ist das gleich doppelt uncool!

**Comment by DO1JLR** [comment]
Ach, das ist euer Problem?

Dann muss ich hier nun entschuldigen. Ich habe eure Frage Falsch verstanden und kann die Situation entschärfen!

Dokuwiki steht unter der GPL Lizenz. Damit ist es eine Freie Software! *(free as in freedom, not in free beer)*
Nikola ist hier die Grundlage für den Static Site Generator (SSD). Dies steht unter der MIT Lizenz und ist damit **auch** Freie Software. *(free as in freedom, not in free beer)*

Als Primärquelle für die Seite wird Markdown verwendet. Es werden aber auch andere Formate unterstützt. Markdown selber steht unter einer BSD-Artigen Lizenz.

Daher entwarnung. Es ist keine properitäre Anwendung wie zum beispiel Slack sondern tatsächlich Freie Software! 

Nikola selber kommt aus dem Jahr 2012, ist damit auch nicht eben entstanden sondern schon ein paar Jahre alt. *([Quelle Nikola Date](https://github.com/getnikola/nikola/commit/a0057662f909b754ebe185f07e233c11758d4a79))*

**Comment by xythobuz** [comment]
Ja, genau, so macht argumentieren viel Spaß.

Dann sag doch auch noch was zum zweiten wichtigen Punkt: nämlich das wir eben genau KEINEN "Static Site Generator" für ein Wiki wollen, weil das, ehrlich gesagt, überhaupt keinen Sinn ergibt.

**Comment by DO1JLR** [comment]
Das mach ich gerne.

Du willst also keinen Static Side Generator. Matt auch nicht. Falko plötzlich auch nicht mehr.
Alex und Ich jedoch schon. (Max wollte früher mal einen, wie er das heute sieht, weiß ich nicht).

Warum du das nicht willst...
Da habe ich bisher von dir und Falko gehört, dass das zu kompliziert sein könnte das Wiki mal eben zu bearbeiten. Also jetzt nicht für euch... aber so allgemein und aus prinzip.

Gut. Für mich ist die Doku oder Mediawiki syntax zu kompliziert. Damit kann ich auch nichts bearbeiten. 

Wir können jetzt auf unseren Standpunkten uns festbeißen und jeder sich weiter mit Drogen voll punpen und weiter jammern oder das ganze ausprobieren.

So ein weiteres Argument ist, dass das alte Wiki früher vermehrt von Hacking und Script-Kiddy angriffen überrumplet wurde.
Das wäre erstmal bei einem git basierten System einfacher zu handeln und ist hier in der Vergangenheit noch nicht vorgekommen.
Aber andererseits sind wir natürlich Deutsch und lernen aus der Vergangenheit? Das ist Sache von Ausländern!

**Comment by DEvil0000** [comment]
also bitte... leute... kann man das auch in ruhe an nem donnerstag besprechen?

ein staric site generator hat vorzeile. warung und angriffs vector sind kleiner. das mit git zu machen erspart einem backups und macht es transparenter und robuster. das mit github zu machen erlaubt es allen die eh schon in der orga sind pushen zu können ohne nochmal iwo daten für nen login hinterlegen zu müssen. außerdem kommt so nen editor mit preview für umsonst mit.
klar ist es anders aber keinesfalls schwerer als in nem üblichen wiki. da haste auch deine markdown oder sonstige formatierungs magic und nen preview aber halt auch all die nachteile. ich glaube nicht daran das es im wesentlichen einfacher zu bedienen ist als die github oder gitlab ui.
es spricht also meiner ansicht nach nichts gegen einen git/github/static site ansatz und wir sollten mal gemeinsam drüber nachdenken und beraten - donnerstags.

**Comment by 205er** [comment]
Sorry, aber wie viele Versuche, dieses Thema zu besprechen, gab es denn schon? Was kam dabei raus? Genau: Nichts!

Überlasst das Thema Wiki doch einfach den Menschen, die sich auch inhaltlich darum kümmern wollen (und das auch in der Vergangenheit getan haben). Hier geht's momentan doch nur darum, dass persönliche Meinungen durchgesetzt werden sollen - und das kann's nicht sein. Bevor wir davon nicht wegkommen, habe ich kein Interesse an einer Neuimplementierung des Wiki

**Comment by DEvil0000** [comment]
@byt3 donnerstag warst du noch recht begeistert von der idee und ich skeptisch.mir geht es bei dem thema nicht um persönliche befindlichkeiten oder meinungenund von in der vergangenheit gut gewartet oder in der vergangenheit drum gekümmert zu sprechen find ich bissel hoch gegriffen. seit ca. 1 monat kümmert sich überhaupt mal wieder jemand. aber das haupt problem sind die inhalte wie ich finde und dass es online bleibt.ich finde jegliche diskussion hier nicht konstruktiv. wenn donnerstags nix bei raus kommt dann hier sicher auch nicht. donnerstag ist der richtige rahmen mit den anwendern. dieses ticket scheint mir hauptsächlich unsachliches kontra geben zu sein ohne wirklich drüber nachzudenken und argumente werden falls vorhanden wohl überlesen.wie schon gesagt hat git vorteile für versionierung, änderungsverfolgung und backup. github/gitlab bringt vorteile für user management und benutzbarkeit. statische seiten sind einfacher und sicherer zu hosten. markdown oder ähnliches ist beides anyway. also was spricht gegen den ansatz außer gewohnheit bzw das wir das eine schon haben?ich bin auf eure konstruktiven Wortmeldungen und eine diskussion am do gespannt.

**Comment by drwuro** [comment]
ganz schöne wall of text hier...

> aber das haupt problem sind die inhalte
wenn das das hauptproblem ist, dann sollte die art und weise wie es gehostet wird doch ziemlich sekundär sein oder nicht?

**Comment by xythobuz** [comment]
ich möchte noch anmerken: unser potentielles wiki hat eigentlich auch öffentliche inhalte, sowie welche die nur intern von Mitgliedern eingesehen werden sollen. Das lässt sich, so wie ich das versteh, mit einem statischen Generator überhaupt nicht abbilden, oder nur sehr umständlich.

Eine History hat ein Dokuwiki genauso. Das ist ja irgendwie auch der Witz davon. Und dazu eine ordentliche Userverwaltung mit Rechten.

**Comment by DO1JLR** [comment]
nicht öffentliche Inhalte ist auch bei beiden Plattformen möglich. sei es mit git-submodule, non-public Repo und SimpleAuth oder einer extra invite-only gruppe im dokuwiki.

Und Microsoft hat den Spam besser in Griff wie das ehemalige Wiki, bei dem irgend jemand zwischen drinnen aus verzweiflung das registrieren abgeschalten hat. Und user dann weinend zu mir gerannt sind, weil sie gerne rein wollten es aber nicht konnten.
Aber da war ja mitarbeiten sooooooo einfach!

**Comment by xythobuz** [comment]
> git-submodule, non-public Repo und SimpleAuth

genau das mein ich mit unschönen hacks. Wir als Informatiker kommen damit zurecht, schon klar. Aber unser Verein hat auch eine Holzwerkstatt, eine Metallwerkstatt, ein Elektroniklabor, und sehr viele Mitglieder die weder git noch github nutzen können. Da kannst du doch nicht noch mit submodules etc. ankommen, oder SimpleAuth.

**Comment by DO1JLR** [comment]
Das mag in deiner zugekifften Realität bestimmt sinn machen.

Mit SimpleAuth und gitmodulen lässt sich dieses von dir erfundene Problem relativ elegant lösen, ohne dass das jemand aus den Werkstatätten überhaupt merkt. Aber über deine hypothetischen Sorgen zu schreiben ist wie gesagt nicht zielführend.

**Comment by xythobuz** [comment]
Alles klar an dieser Stelle ist die Diskussion für mich auch endgültig beendet. Viel Spaß noch.

**Comment by 205er** [comment]
> [...] seit ca. 1 monat kümmert sich überhaupt mal wieder jemand. [...]

Das kann ich so nicht stehen lassen!
Es haben sich sehr wohl Leute um das Wiki gekümmert, wir haben Zeit und Arbeit in das Thema investiert. Nur, weil du es vielleicht nicht mitbekommen hast, bedeutet das nicht, dass nichts passiert ist. Allerdings wurden diesen Bestrebungen, wo es nur ging, Steine in den Weg gelegt. Nicht nur, dass der Beirat das Anliegen der Mitglieder nicht unterstützt hat, nein - es wurde auch sabotiert, es gab persönliche Anfeindungen und aufkommende Diskussionen wurden direkt im Keim erstickt...

Nachvollziehbar, dass jetzt keiner mehr Lust auf eine "Friss oder Stirb"-Lösung hat?

**Comment by DO1JLR** [comment]
Sicherlich hat jeder von uns sehr viel Arbeit in das Wiki gesteckt.

Erst letzten Donnerstag zum Beispiel, als wir zusammen dieses Repo angelegt haben...

Lass uns das doch nächsten Donnerstag fortsetzen und bis dahin dieses toxische gehate lassen.

Danke
