### ISSUE TITLE
siehe Issue 01 - der immer noch nicht bearbeitet wurde, aber schon geschlossen wurde

### ISSUE THREAD

**Issue by rtt-mmk** [ToolboxBodensee/toolbox-wiki#2]
siehe https://github.com/ToolboxBodensee/toolbox-wiki/issues/1
der aus irgendwie, komischweise geschlossen wurde, ohne auf die beiden wichtigsten Fragen, Anforderungen an ein komplett neues Wiki zu antworten.

Die beiden wichtigsten Fragen sind leider nach wie vor und wie immer von Dir, Lilian, bis heute nicht beantwortet worden:

1. Ihr übernehmt dann auch alle Inhalte vom Wiki in das neue selbst programmierte?
2. Und habt dort integriert einen Markup-Seiteneditor (oder WYSIWYG) in dem auch jedes Mitglied das Wiki so wie im Dokuwiki editieren kann?
3. Warum nicht einfach die Links des Wikis auf wiki.byt3.de setzten, wo derzeit das vollständige Toolbox-wiki mit allen bisherigen Inhalten läuft?

**Comment by DO1JLR** [comment]
Was jetzt? #1 oder nicht???
