### ISSUE TITLE
wiki Nutzung

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-wiki#4]
In Bezug auf das Wiki ist die aktuelle Entscheidung weiterhin das Dokuwiki zu nutzen und nicht auf Nikola als Static Site Generator umzusteigen. (das soll lediglich als Hinweis dienen, damit hier keiner im Glauben, dass dies sicher auch in der TB genutzt wird viel Zeit versenkt)

**Comment by DO1JLR** [comment]
Mit dem Falko habe ich über das Thema letzten Donnerstag gesprochen, da war die Aussage gegenteilig und dass soweit nichts gegen den SSG spricht...

Diese Entscheidung kommt jetzt von wo?

**Comment by maxbachmann** [comment]
Also mein Stand ist der von der Leitungssitzung.

**Comment by DO1JLR** [comment]
Mein stand ist von dem Gespräch mit Falko nach der Leitungssitzung... ``¯\_(ツ)_/¯``

**Comment by 205er** [comment]
In der Leitungssitzung wurde entschieden, dass alles so bleibt wie's ist. Ich habe dir nie gesagt, dass wir die technische Basis umstellen sollen! Bitte investiere keine Zeit in dieses Thema. Es gibt sicher viele Issues, die deine Aufmerksamkeit nötiger haben.

**Comment by 205er** [comment]
Inhaltliche Mitarbeit ist natürlich immer gern gesehen und du bis herzlich eingeladen deinen Input beizusteuern.

**Comment by DO1JLR** [comment]
> Inhaltliche Mitarbeit ist natürlich immer gern gesehen und du bis herzlich eingeladen deinen Input beizusteuern.

gut... inhaltliche Mitarbeit habe ich hier geliefert. auf den anderen wikisystemen habe ich leider kein schreibzugriff oder teilweise noch nicht mal einen account.

Wenn das so ist, wie es aktuell ist... dann frag ich mich zwar wie es das 'Problem' lösen soll... aber egal.
Dann habt ihr das so entschieden und ich werde an dem jetzigen Aufbau nichts ändern.

**Comment by rtt-mmk** [comment]
genau das war auch das, warum ich im vorherigen Issue gefragt habe, warum man was eigenes programmiert (programmieren will), wenn es etwas Fertiges gibt.

**Comment by 205er** [comment]
Du hast Schreibzugriff... Mit der Bitte Vandalismus zukünftig zu unterlassen.
Danke!

**Comment by DO1JLR** [comment]
ich habe zumindest nicht die selben permissions wie im alten wiki. 

letztes mal hieß es, das man leute da nicht unangekündigt raus werfen will... aber das weiß vermutlich auch keiner mehr!

**Comment by rtt-mmk** [comment]
Achtung: Off-Topic, aber das es gerade passt:
> ich habe zumindest nicht die selben permissions wie im alten wiki.
> letztes mal hieß es, das man leute da nicht unangekündigt raus werfen will... aber das weiß vermutlich auch keiner mehr!

Doch, aber nachdem ich vergangenen Sonntag gesehen habe, was am Samstag auf dem os-2.tbbs.me gelöscht und gemacht wurde sowie auf welche Art und Weise, hast du seitdem auch keine Admin- und Root-Rechte mehr auf den os-[2-5]-Servern im Keller. Zur Info.

**Comment by 205er** [comment]
Da du zweimal komplette Seiten gelöscht hast, statt sie (inhaltlich vernünftig) zu überarbeiten, gab's temporär mal keinen Schreibzugriff für dich... Anders wusst ich mir hier leider nicht zu helfen. Grundlos war's jedenfalls nicht... Schade ist's trotzdem...

**Comment by DO1JLR** [comment]
dann irgnorier mich halt.

> Achtung: Off-Topic, aber da es gerade passt:
> 
> > ich habe zumindest nicht die selben permissions wie im alten wiki.
> > letztes mal hieß es, das man leute da nicht unangekündigt raus werfen will... aber das weiß vermutlich auch keiner mehr!
> 
> Doch, aber nachdem ich vergangenen Sonntag gesehen habe, was am Samstag auf dem os-2.tbbs.me gelöscht und gemacht wurde sowie auf welche Art und Weise, hast du seitdem auch keine Admin- und Root-Rechte mehr auf den os-[2-5]-Servern im Keller. Zur Info.

Sehr off-topic.

Für dich zur info:
nach dem ich gesehen habe was du - als mein user- auf den os 2-5 servern gemacht hast hast wirst du auch keine zugriffe oder support mehr bekommen und die ansible secrets werden wohl erneuert werden müssen, da sie dort im klartext rumliegen!

Meine Switche sind auch tabu für dich!

**Comment by rtt-mmk** [comment]
> Für dich zur info:
> nach dem ich gesehen habe was du - als mein user- auf den os 2-5 servern gemacht hast hast wirst du auch keine zugriffe oder support mehr bekommen und die ansible secrets werden wohl erneuert werden müssen, da sie dort im klartext rumliegen!
> Meine Switche sind auch tabu für dich!

Deine Switche?? Was? Du weißt schon, wie das ofiziell mit Geräten, die in der Toolbox eingebaut sind, geregelt ist. Die gehören daher dem Verein. Kannst du entsprechend auch offiziell nachlesen. 

Als dein User?? Häh, ich war nie als Dein User irgendwo. 
Lilian, diese Server liegen im internen Netz der Toolbox. Schön, dass du dem nicht vertraust. Und noch viel schlimmer, woher weißt du dass unter meinem Nutzeraccount was unverschlüsselt rumliegt. D.h. Du musst dich darin umgesehen haben, ohne mit mir zu sprechen!

Btw. es ist mal ganz gut, wenn die Secrets noch wer zusätzlich hat. Vor allem der Vorstand - das Router-Passwort hätten wir alle auch mal ganz gerne ausgehändigt (nicht unbedingt ich, aber gerne weitere Leute/Vorstände vor Ort). Ich brauche die Secrets zu den Switchen nicht, solange die Config in Ordnung ist und bleibt, ich per SSH(oder VPN) hinkomme und die Dienste für alle auf den Servern im Keller sauber laufen können.

Dass du Secrets einfach mal ändern willst, interpretiere ich mal so, dass mal wieder Leute gehindert werden sollen, was zu verbessern.

**Comment by rtt-mmk** [comment]
Ich möchste jedenfalls ungern schon wieder in Richtung was melden müssen...das ist doch kindisch, hier ständig was raushängen zu lassen, nur weil man der einzige ist, der Zugang zu bestimmten Geräten hat.

Außerdem kannst du dir deine Commits vom 10. Oktober u.a. in #63 ins Toolbox-Netzwerk-Ansible mal anschauen - seit dem habe ich gar keinen Zugriff mehr auf die Switche! 

Das hast du selbst geändert und ohne Review gemergt. Also was willst Du?

**Comment by rtt-mmk** [comment]
Hast Du, Lilian, das Syslog gelöscht?
